package com.worldcup.service;

import java.util.Map;

/**
 * Globalny slownik reprezentacji narodowych: polska nazwa -> kod ISO flagi (flagcdn.com).
 * Niezalezny od konkretnego turnieju - kazde rozgrywki maja wlasny, dowolny podzbior
 * druzyn wybierany z tej listy w panelu admina (patrz AdminController#listCountries),
 * co gwarantuje poprawny kod ISO (i przez to flage) bez recznego wpisywania.
 */
public final class CountryCatalog {

    private CountryCatalog() {
    }

    public static final Map<String, String> CODES = Map.ofEntries(
            // Europa
            Map.entry("Albania", "al"),
            Map.entry("Andora", "ad"),
            Map.entry("Anglia", "gb-eng"),
            Map.entry("Armenia", "am"),
            Map.entry("Austria", "at"),
            Map.entry("Azerbejdżan", "az"),
            Map.entry("Belgia", "be"),
            Map.entry("Białoruś", "by"),
            Map.entry("Bośnia i Hercegowina", "ba"),
            Map.entry("Bułgaria", "bg"),
            Map.entry("Chorwacja", "hr"),
            Map.entry("Cypr", "cy"),
            Map.entry("Czarnogóra", "me"),
            Map.entry("Czechy", "cz"),
            Map.entry("Dania", "dk"),
            Map.entry("Estonia", "ee"),
            Map.entry("Finlandia", "fi"),
            Map.entry("Francja", "fr"),
            Map.entry("Gibraltar", "gi"),
            Map.entry("Grecja", "gr"),
            Map.entry("Gruzja", "ge"),
            Map.entry("Hiszpania", "es"),
            Map.entry("Holandia", "nl"),
            Map.entry("Irlandia", "ie"),
            Map.entry("Irlandia Północna", "gb-nir"),
            Map.entry("Islandia", "is"),
            Map.entry("Izrael", "il"),
            Map.entry("Kazachstan", "kz"),
            Map.entry("Kosowo", "xk"),
            Map.entry("Liechtenstein", "li"),
            Map.entry("Litwa", "lt"),
            Map.entry("Luksemburg", "lu"),
            Map.entry("Łotwa", "lv"),
            Map.entry("Macedonia Północna", "mk"),
            Map.entry("Malta", "mt"),
            Map.entry("Mołdawia", "md"),
            Map.entry("Monako", "mc"),
            Map.entry("Niemcy", "de"),
            Map.entry("Norwegia", "no"),
            Map.entry("Polska", "pl"),
            Map.entry("Portugalia", "pt"),
            Map.entry("Rosja", "ru"),
            Map.entry("Rumunia", "ro"),
            Map.entry("San Marino", "sm"),
            Map.entry("Serbia", "rs"),
            Map.entry("Słowacja", "sk"),
            Map.entry("Słowenia", "si"),
            Map.entry("Szkocja", "gb-sct"),
            Map.entry("Szwajcaria", "ch"),
            Map.entry("Szwecja", "se"),
            Map.entry("Turcja", "tr"),
            Map.entry("Ukraina", "ua"),
            Map.entry("Walia", "gb-wls"),
            Map.entry("Węgry", "hu"),
            Map.entry("Włochy", "it"),
            Map.entry("Wyspy Owcze", "fo"),

            // Ameryka Południowa
            Map.entry("Argentyna", "ar"),
            Map.entry("Boliwia", "bo"),
            Map.entry("Brazylia", "br"),
            Map.entry("Chile", "cl"),
            Map.entry("Ekwador", "ec"),
            Map.entry("Kolumbia", "co"),
            Map.entry("Paragwaj", "py"),
            Map.entry("Peru", "pe"),
            Map.entry("Urugwaj", "uy"),
            Map.entry("Wenezuela", "ve"),

            // Ameryka Północna, Środkowa i Karaiby
            Map.entry("USA", "us"),
            Map.entry("Meksyk", "mx"),
            Map.entry("Kanada", "ca"),
            Map.entry("Kostaryka", "cr"),
            Map.entry("Panama", "pa"),
            Map.entry("Honduras", "hn"),
            Map.entry("Jamajka", "jm"),
            Map.entry("Haiti", "ht"),
            Map.entry("Curacao", "cw"),
            Map.entry("Trynidad i Tobago", "tt"),
            Map.entry("Salwador", "sv"),
            Map.entry("Gwatemala", "gt"),
            Map.entry("Nikaragua", "ni"),
            Map.entry("Kuba", "cu"),
            Map.entry("Surinam", "sr"),
            Map.entry("Dominikana", "do"),
            Map.entry("Bermudy", "bm"),

            // Afryka
            Map.entry("Maroko", "ma"),
            Map.entry("Algieria", "dz"),
            Map.entry("Tunezja", "tn"),
            Map.entry("Egipt", "eg"),
            Map.entry("Senegal", "sn"),
            Map.entry("Nigeria", "ng"),
            Map.entry("Ghana", "gh"),
            Map.entry("Wybrzeże Kości Słoniowej", "ci"),
            Map.entry("Kamerun", "cm"),
            Map.entry("Mali", "ml"),
            Map.entry("Republika Zielonego Przylądka", "cv"),
            Map.entry("RPA", "za"),
            Map.entry("DR Konga", "cd"),
            Map.entry("Gwinea", "gn"),
            Map.entry("Burkina Faso", "bf"),
            Map.entry("Gabon", "ga"),
            Map.entry("Zambia", "zm"),
            Map.entry("Mozambik", "mz"),
            Map.entry("Gwinea Równikowa", "gq"),
            Map.entry("Benin", "bj"),
            Map.entry("Angola", "ao"),
            Map.entry("Kongo", "cg"),
            Map.entry("Tanzania", "tz"),
            Map.entry("Uganda", "ug"),
            Map.entry("Namibia", "na"),
            Map.entry("Zimbabwe", "zw"),
            Map.entry("Etiopia", "et"),
            Map.entry("Kenia", "ke"),
            Map.entry("Sudan", "sd"),
            Map.entry("Libia", "ly"),
            Map.entry("Mauretania", "mr"),
            Map.entry("Togo", "tg"),
            Map.entry("Niger", "ne"),
            Map.entry("Czad", "td"),
            Map.entry("Rwanda", "rw"),
            Map.entry("Komory", "km"),
            Map.entry("Madagaskar", "mg"),
            Map.entry("Sierra Leone", "sl"),
            Map.entry("Gambia", "gm"),
            Map.entry("Gwinea Bissau", "gw"),
            Map.entry("Sudan Południowy", "ss"),
            Map.entry("Erytrea", "er"),
            Map.entry("Dżibuti", "dj"),
            Map.entry("Somalia", "so"),
            Map.entry("Republika Środkowoafrykańska", "cf"),
            Map.entry("Seszele", "sc"),
            Map.entry("Mauritius", "mu"),
            Map.entry("Burundi", "bi"),
            Map.entry("Malawi", "mw"),
            Map.entry("Botswana", "bw"),
            Map.entry("Lesotho", "ls"),
            Map.entry("Eswatini", "sz"),
            Map.entry("Sao Tome i Principe", "st"),

            // Azja
            Map.entry("Japonia", "jp"),
            Map.entry("Korea Południowa", "kr"),
            Map.entry("Korea Północna", "kp"),
            Map.entry("Iran", "ir"),
            Map.entry("Arabia Saudyjska", "sa"),
            Map.entry("Katar", "qa"),
            Map.entry("Irak", "iq"),
            Map.entry("Jordania", "jo"),
            Map.entry("Uzbekistan", "uz"),
            Map.entry("Chiny", "cn"),
            Map.entry("Indie", "in"),
            Map.entry("Indonezja", "id"),
            Map.entry("Tajlandia", "th"),
            Map.entry("Wietnam", "vn"),
            Map.entry("Malezja", "my"),
            Map.entry("Kuwejt", "kw"),
            Map.entry("Zjednoczone Emiraty Arabskie", "ae"),
            Map.entry("Oman", "om"),
            Map.entry("Bahrajn", "bh"),
            Map.entry("Syria", "sy"),
            Map.entry("Liban", "lb"),
            Map.entry("Palestyna", "ps"),
            Map.entry("Kirgistan", "kg"),
            Map.entry("Tadżykistan", "tj"),
            Map.entry("Turkmenistan", "tm"),
            Map.entry("Afganistan", "af"),
            Map.entry("Bangladesz", "bd"),
            Map.entry("Filipiny", "ph"),
            Map.entry("Singapur", "sg"),
            Map.entry("Hongkong", "hk"),
            Map.entry("Tajwan", "tw"),
            Map.entry("Nepal", "np"),
            Map.entry("Mongolia", "mn"),
            Map.entry("Jemen", "ye"),
            Map.entry("Pakistan", "pk"),
            Map.entry("Sri Lanka", "lk"),
            Map.entry("Kambodża", "kh"),
            Map.entry("Laos", "la"),
            Map.entry("Mjanma", "mm"),
            Map.entry("Malediwy", "mv"),
            Map.entry("Bhutan", "bt"),
            Map.entry("Brunei", "bn"),

            // Oceania
            Map.entry("Australia", "au"),
            Map.entry("Nowa Zelandia", "nz"),
            Map.entry("Fidżi", "fj"),
            Map.entry("Papua-Nowa Gwinea", "pg"),
            Map.entry("Wyspy Salomona", "sb"),
            Map.entry("Vanuatu", "vu"),
            Map.entry("Nowa Kaledonia", "nc"),
            Map.entry("Tahiti", "pf"),
            Map.entry("Samoa", "ws"),
            Map.entry("Samoa Amerykańskie", "as"),
            Map.entry("Wyspy Cooka", "ck"),
            Map.entry("Tonga", "to")
    );
}
